---
title: "Homework 6"
author: "Jeffrey Chang"
date: "4/4/2020"
output: pdf_document
---
```{r echo=FALSE}
rm(list=ls())
library(bookdown)
library(PoEdata)#for PoE datasets
library(knitr) #for referenced tables with kable()
library(xtable) #makes data frame for kable
library(printr) #automatically prints output nicely
library(effects)
library(car)
library(AER)
library(broom) #for tidy lm output and function glance()
library(stats)
library(lmtest)#for coeftest() and other test functions
library(stargazer) #nice and informative tables
```

```{r}
# Check the metrics.dat dataset.
data("metrics", package="PoEdata")
```


EXERCISE 7.15: 
```{r}
# Check the br2.dat dataset.
library(foreign)
br2 <- read.dta("br2.dta")
summary(br2)
```

```{r}
# Compute a histogram of 'br2$price'
library(ggplot2)
library(moments)
skewness(br2$price)
qplot(br2$price, geom="histogram",  main = 'The skewness of price is 6.2919' ,col=I("blue"))

```

```{r}
mod1 <- lm(log(price/1000)~sqft+bedrooms+baths+age+owner+pool+traditional+fireplace+waterfront, data=br2)
kable(tidy(mod1), caption="A Regression Model", digits=4)
```

```{r}
summary(mod1)
```

```{r}
# create new model table (traditional*waterfront)
mod2 <- lm(log(price/1000)~sqft+bedrooms+baths+age+owner+pool+traditional+fireplace+waterfront+traditional*waterfront, data=br2)
kable(tidy(mod2), caption="A Regression Model_2 ", digits=4)
```

```{r}
mod3 <- lm(log(price/1000)~sqft+bedrooms+baths+age+owner+pool+fireplace+waterfront, data=br2) # no traditional variable

dnotrad <- br2[which(br2$traditional==0),]
dtrad <- br2[which(br2$traditional==1),] 

mod5not <- lm(log(price/1000)~sqft+bedrooms+baths+age+owner+pool+traditional+fireplace+waterfront+traditional*waterfront, data=dnotrad)# traditional=0 

mod5t <- lm(log(price/1000)~sqft+bedrooms+baths+age+owner+pool+traditional+fireplace+waterfront+traditional*waterfront, data=dtrad)#traditional=1 

mod6 <-lm(log(price/1000)~sqft+bedrooms+baths+age+owner+pool+fireplace+waterfront+traditional*waterfront+traditional/
            (sqft+bedrooms+baths+age+owner+pool+fireplace+waterfront+traditional*waterfront), data=br2)


stargazer(mod3, mod5t, mod5not, mod6, header=FALSE,
type='text',
title="Model comparison, 'Price' equation",
keep.stat="n",digits=2, single.row=TRUE,
intercept.bottom=FALSE)
```

```{r}
mod3 <- lm(log(price/1000)~sqft+bedrooms+baths+age+owner+pool+fireplace+waterfront, data=br2)
kable(anova(mod3, mod6),
caption="Chow test for the 'Price' equation")
```

EXERCISE 7.16: 

```{r}
stt4 <- read.dta("stockton4.dta")
library(gridExtra)
price <- stt4$sprice
log_price <- stt4$sprice
skewness(stt4$sprice)
plot1 <- qplot(price, geom="histogram",  main = 'The skewness of price is 3.5566' ,col=I("red"))
plot2 <- qplot(log_price, log = 'x', geom="histogram",  main = 'A histogram of log(price)' ,col=I("red"))
grid.arrange(plot1, plot2, ncol=2)
```

```{r}
mod7 <- lm(log(price/1000)~livarea+beds+baths+lgelot+age+pool, data=stt4)
kable(tidy(mod7), caption="A Regression Model_7.16(b) ", digits=4)
```

```{r}
mod8 <- lm(log(price/1000)~livarea+beds+baths+lgelot+age+pool+lgelot*livarea, data=stt4)
kable(tidy(mod8), caption="A Regression Model_7.16(d) ", digits=4)
```

```{r}
mod9 <- lm(log(sprice/1000)~livarea+beds+baths+age+pool, data=stt4) # no lot

dnolot <- stt4[which(stt4$lgelot==0),]
dlot <- stt4[which(stt4$lgelot==1),] 

mod10n <- lm(log(sprice/1000)~ livarea+beds+baths+lgelot+age+pool+(lgelot*livarea), data=dnolot)# lot=0 

mod10<-lm(log(sprice/1000)~livarea+beds+baths+lgelot+age+pool+(lgelot*livarea), data=dlot) #lot=1 

mod11 <- lm(log(sprice/1000)~livarea+beds+baths+age+pool+lgelot*livarea+lgelot/(livarea+beds+baths+age+pool+lgelot*livarea)
            ,data = stt4)

stargazer(mod9, mod10, mod10n, mod11, header=FALSE,
type='text',
title="Model comparison, 'sprice' equation",
keep.stat="n",digits=2, single.row=TRUE,
intercept.bottom=FALSE)
```

```{r}
kable(anova(mod9, mod11),
caption="Chow test for the 'sPrice' equation")
```

