---
title: "Homework 8"
author: "Jeffrey Chang"
date: "4/9/2020"
output: pdf_document
---

```{r}
library(foreign) # read.dta()
library(ggplot2)
library(AER) #for `ivreg()`
library(broom) #for `glance(`) and `tidy()`
library(knitr) #for making neat tables with `kable()`
```

Question 10.6
```{r}
iv2 <- read.dta("ivreg2.dta")
iv2$e = iv2$y-3-iv2$x
cor(iv2$x,iv2$e)
```


```{r}
my_graph <- 
  ggplot(iv2, mapping = aes(x = x, y = y)) +
  geom_point(color = '#2185c4')+ 
  geom_abline(intercept = 3, slope = 1, color="red")+
  geom_smooth(method = "lm", se = FALSE, color="yellow")+
  geom_point(iv2, mapping = aes(x, y-e), col = 'red') 
my_graph         
```

Question 10.6(d)
```{r}
# N = 10
mod10 <- lm(y~x, data=iv2[1:10,])
kable(tidy(mod10), caption="N = 10", digits=4)
# N = 20
mod20 <- lm(y~x, data=iv2[1:20,])
kable(tidy(mod20), caption="N = 20", digits=4)
# N = 100
mod100 <- lm(y~x, data=iv2[1:100,])
kable(tidy(mod100), caption="N =100", digits=4)
# N = 500
mod500 <- lm(y~x, data=iv2)
kable(tidy(mod500), caption="N = 500", digits=4)
```

Question 10.6(e)
```{r}
res <- cor(iv2)
round(res, 4)
```

Question 10.6(f) (z1)
```{r}
# N = 10
mod10z1 <- ivreg(y~x | z1, data=iv2[1:10,])
kable(tidy(mod10z1), caption="N = 10", digits=4)
# N = 20
mod20z1 <- ivreg(y~x | z1, data=iv2[1:20,])
kable(tidy(mod20z1), caption="N = 20", digits=4)
# N = 100
mod100z1 <- ivreg(y~x | z1, data=iv2[1:100,])
kable(tidy(mod100z1), caption="N =100", digits=4)
# N = 500
mod500z1 <- ivreg(y~x | z1, data=iv2)
kable(tidy(mod500z1), caption="N = 500", digits=4)

```

Question 10.6(g) (z2)
```{r}
# N = 10
mod10z2 <- ivreg(y~x | z2, data=iv2[1:10,])
kable(tidy(mod10z2), caption="N = 10", digits=4)
# N = 20
mod20z2 <- ivreg(y~x | z2, data=iv2[1:20,])
kable(tidy(mod20z2), caption="N = 20", digits=4)
# N = 100
mod100z2 <- ivreg(y~x | z2, data=iv2[1:100,])
kable(tidy(mod100z2), caption="N =100", digits=4)
# N = 500
mod500z2 <- ivreg(y~x | z2, data=iv2)
kable(tidy(mod500z2), caption="N = 500", digits=4)

```

Question 10.6(h) (z1+z2)
```{r}
# N = 10
mod10z1z2 <- ivreg(y~x | z1+z2, data=iv2[1:10,])
kable(tidy(mod10z1z2), caption="N = 10", digits=4)
# N = 20
mod20z1z2 <- ivreg(y~x | z1+z2, data=iv2[1:20,])
kable(tidy(mod20z1z2), caption="N = 10", digits=4)
# N = 100
mod100z1z2 <- ivreg(y~x | z1+z2, data=iv2[1:100,])
kable(tidy(mod100z1z2), caption="N = 10", digits=4)
# N = 500
mod500z1z2 <- ivreg(y~x | z1+z2, data=iv2)
kable(tidy(mod500z1z2), caption="N = 10", digits=4)
```